### ISSUE TITLE
NX v18 support

### ISSUE THREAD

**Issue by rexizam** [TheUnderScorer/nx-semantic-release#107]
Hello I've been using this plugin with NX v17 and it was working great until I updated NX to v18. Now I get the following error:

```
With additional flags:
  --branches=hotfix/RDUX-10160/bump-all-package-versions
> nx run analytics-flyout-panel:semantic-release --branches=hotfix/RDUX-10160/bump-all-package-versions
[4:55:57 PM] [semantic-release] › ℹ  Running semantic-release version 20.1.0
[4:55:57 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:55:57 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[4:55:58 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:55:58 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:55:58 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[4:55:58 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:55:58 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[4:56:02 PM] [semantic-release] › ✔  Run automated release from branch hotfix/RDUX-10160/bump-all-package-versions on repository git@gitlab.stibo.dk:step/tim/web-ui-react-components.git
[4:56:03 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:56:03 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:56:03 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[4:56:03 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[4:56:03 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.stibo.dk/api/v4)
[4:56:03 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[4:56:03 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[4:56:03 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[4:56:03 PM] [semantic-release] › ℹ  No git tag version found on branch hotfix/RDUX-10160/bump-all-package-versions
[4:56:03 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[4:56:03 PM] [semantic-release] › ℹ  Found 172 commits since last release
[4:56:03 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[4:56:03 PM] [semantic-release] › ✘  Failed step "analyzeCommits" of plugin "[Function: nx-semantic-release]"
[4:56:03 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /builds/step/tim/web-ui-react-components/node_modules/@semantic-release/commit-analyzer/index.js from /builds/step/tim/web-ui-react-components/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /builds/step/tim/web-ui-react-components/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at nx-semantic-release (/builds/step/tim/web-ui-react-components/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///builds/step/tim/web-ui-react-components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///builds/step/tim/web-ui-react-components/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///builds/step/tim/web-ui-react-components/node_modules/@theunderscorer/nx-semantic-release/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: nx-semantic-release]'
}
 NX   require() of ES Module /builds/step/tim/web-ui-react-components/node_modules/@semantic-release/commit-analyzer/index.js from /builds/step/tim/web-ui-react-components/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /builds/step/tim/web-ui-react-components/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
Pass --verbose to see the stacktrace.
```

```
"devDependencies": {
    "@nx/js": "18.0.6",
    "@semantic-release/gitlab": "9.5.1",
    "@theunderscorer/nx-semantic-release": "2.10.0",
    "nx": "18.0.6"
  }
```

**Comment by rexizam** [comment]
Hi,I have the following versions installed:

@semantic-release/commit-analyzer@9.0.2
semantic-release-plugin-decorators@3.0.1

Apparently my dependencies were messed up and I had the wrong versions of commit-analyzer and plugin-decorators installed even though I did a clean install after migrating NX to v18.
