### ISSUE TITLE
Error ERR_REQUIRE_ESM]: require() of ES Module ...

### ISSUE THREAD

**Issue by josh-houseworks** [TheUnderScorer/nx-semantic-release#110]
Hello,

I am trying to use this alongside NX and this plugin for SR. https://github.com/droidsolutions/semantic-release-nuget

However when I am trying to run semantic release i am getting...

```
An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/josh/Desktop/nx/masterdata/node_modules/@droidsolutions-oss/semantic-release-nuget/dist/index.mjs not supported.
Instead change the require of /Users/josh/Desktop/nx/masterdata/node_modules/@droidsolutions-oss/semantic-release-nuget/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at nx-semantic-release (/Users/josh/Desktop/nx/masterdata/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///Users/josh/Desktop/nx/masterdata/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///Users/josh/Desktop/nx/masterdata/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///Users/josh/Desktop/nx/masterdata/node_modules/@theunderscorer/nx-semantic-release/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: nx-semantic-release]'
}
```

I saw a similar issue that seemed to indicate that this project isnt converted to ESM and wont work with ESM packages? I am not very familiar with node programming so sorry if this is possibly a silly question. 

Thanks

**Comment by marinakon0302** [comment]
We also failed to this issue
we use the latest nx-semantic-release plugin 2.11.0
```
11:21:02  [8:20:53 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/****/agent/workspace/elines_unify_rc-test-sr-from-dev/node_modules/@semantic-release/npm/index.js from /home/****/agent/workspace/elines_unify_rc-test-sr-from-dev/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
11:21:02   NX   require() of ES Module /home/****/agent/workspace/elines_unify_rc-test-sr-from-dev/node_modules/@semantic-release/npm/index.js from /home/****/agent/workspace/elines_unify_rc-test-sr-from-dev/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
```

**Comment by marinakon0302** [comment]
as a workaround we've added `"semantic-release-plugin-decorators": "^4.0.0"` as devDependencies to our project package.json
