### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by MarcosRava** [TheUnderScorer/nx-semantic-release#30]
since this week we are receiving this error from github actions using action [nx-semantic-release](https://github.com/TheUnderScorer/nx-semantic-release) (it was working normally before)
```
[1:07:46 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.3
[1:07:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[1:07:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[1:07:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[1:07:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[1:07:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[1:07:47 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[1:07:47 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/kovihq/nestjs-modules.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kovihq/nestjs-modules.git/'
    at makeError (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBranches (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/semantic-release/lib/git.js:66:11)
    at async module.exports (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/semantic-release/lib/branches/expand.js:6:23)
    at async module.exports (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/semantic-release/lib/branches/index.js:14:26)
    at async run (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/semantic-release/index.js:65:22)
    at async module.exports (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/semantic-release/index.js:269:22)
    at async semanticRelease (/home/runner/work/nestjs-modules/nestjs-modules/node_modules/@theunderscorer/nx-semantic-release/src/executors/semantic-release/semantic-release.js:33:5) {
  shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/kovihq/nestjs-modules.git',
  command: 'git ls-remote --heads https://x-access-token:[secure]@github.com/kovihq/nestjs-modules.git',
  escapedCommand: 'git ls-remote --heads "https://x-access-token:[secure]@github.com/kovihq/nestjs-modules.git"',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: Invalid username or password.\n' +
    "fatal: Authentication failed for 'https://github.com/kovihq/nestjs-modules.git/'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}


```

The step is

```yml
      
      - name: release
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: |
          npx nx affected --target=semantic-release --parallel=1
```

I tried to use a PAT with full access, but the error persists

Some idea to fix this? There is something wrong with my step?

Tks

**Comment by TheUnderScorer** [comment]
Hey @MarcosRava!

Did you try to play around with the checkout step in your CI? Usually setting `persist-credentials` to `false` helps:

```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
```

**Comment by MarcosRava** [comment]
@TheUnderScorer I think that it was something related to github action instabilities, now it's working again
Tks, I'll close this issue
