### ISSUE TITLE
Lack os ESM support on dependency

### ISSUE THREAD

**Issue by drochetti** [TheUnderScorer/nx-semantic-release#55]
The `semantic-release-plugin-decorators` lacks support for ESM modules, there is an open issue there (https://github.com/pmowrer/semantic-release-plugin-decorators/issues/32) but apparently it's not getting much traction. Is there a known workaround or a plan to avoid ESM issues going forward?

The error I get:

```plain
An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /dev/fal-ai/serverless-js/node_modules/@semantic-release/npm/index.js from /dev/fal-ai/serverless-js/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /dev/fal-ai/serverless-js/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at nx-semantic-release (/dev/fal-ai/serverless-js/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///dev/fal-ai/serverless-js/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///dev/fal-ai/serverless-js/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///dev/fal-ai/serverless-js/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: nx-semantic-release]'
}
```

**Comment by goestav** [comment]
I ran into the same issue and I made a fork of this repo with [the patch from this comment](https://github.com/pmowrer/semantic-release-plugin-decorators/issues/32#issuecomment-1531476744).
The package is available [on NPM](https://www.npmjs.com/package/@goestav.x/nx-semantic-release) and I updated the instructions in the readme file of [the github repository](https://github.com/goestav/nx-semantic-release#installation).

**Comment by eemelipa** [comment]
A workaround for the `semantic-release-plugin-decorators` ESM issue could be copy-pasting the `wrapStep.js` file to this repo then fixing the copied file.

**Comment by dtap001** [comment]
Then what to do? I am failing with the same error:
[5:42:49 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/gcl/gcl/node_modules/@semantic-release/commit-analyzer/index.js from /home/runner/work/gcl/gcl/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.
Instead change the require of index.js in /home/runner/work/gcl/gcl/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
    at nx-semantic-release (/home/runner/work/gcl/gcl/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:49:24)
    at validator (file:///home/runner/work/gcl/gcl/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///home/runner/work/gcl/gcl/node_modules/@theunderscorer/nx-semantic-release/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (file:///home/runner/work/gcl/gcl/node_modules/@theunderscorer/nx-semantic-release/node_modules/p-reduce/index.js:16:10) {
  code: 'ERR_REQUIRE_ESM',
  pluginName: '[Function: nx-semantic-release]'
}

 >  NX   require() of ES Module /home/runner/work/gcl/gcl/node_modules/@semantic-release/commit-analyzer/index.js from /home/runner/work/gcl/gcl/node_modules/semantic-release-plugin-decorators/src/wrapStep.js not supported.

   Instead change the require of index.js in /home/runner/work/gcl/gcl/node_modules/semantic-release-plugin-decorators/src/wrapStep.js to a dynamic import() which is available in all CommonJS modules.
   Pass --verbose to see the stacktrace.


 

 >  NX   Running target semantic-release for 2 projects failed

**Comment by eemelipa** [comment]
The upstream [issue](https://github.com/pmowrer/semantic-release-plugin-decorators/issues/32) got fixed. It might be possible to make some progress now

**Comment by eemelipa** [comment]
This issues shouldn't be stale

**Comment by philwronski** [comment]
Same error here. Can you add the @goestav fix please ?
