### ISSUE TITLE
 Invalid host defined options

### ISSUE THREAD

**Issue by tyteen4a03** [TheUnderScorer/nx-semantic-release#81]
For some reason I'm getting this error when trying to run `nx g @theunderscorer/nx-semantic-release:install --verbose`:

```
✔ Would you want to enforce conventional commits? (Y/n) · true
✔ What is the remote repository url? (example: https://github.com/TheUnderScorer/nx-semantic-release) · https://github.com/tyteen4a03/myrepo
✔ Would you want to create github releases? (Y/n) · true
✔ Would you want to create changelog file? (Y/n) · true
✔ Would you want to create npm releases? (Y/n) · false

 >  NX   Invalid host defined options


TypeError: Invalid host defined options
    at Object.<anonymous> (/Users/tyteen4a03/Documents/myrepo/node_modules/prettier/index.cjs:600:23)
    at Module._compile (/Users/tyteen4a03/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Mod.require (/Users/tyteen4a03/Documents/myrepo/node_modules/nx/bin/init-local.js:207:36)
    at require (/Users/tyteen4a03/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /Users/tyteen4a03/Documents/myrepo/node_modules/@theunderscorer/nx-semantic-release/node_modules/@nx/devkit/src/generators/format-files.js:18:59
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by TheUnderScorer** [comment]
LOL, this is a weird error 😄. It seems to be caused by prettier, as per [this](https://github.com/prettier/prettier-vscode/issues/3114) issue. Could you try solutions that were mentioned in it?
