### ISSUE TITLE
analyzeCommits fails to Error: spawn EBADF

### ISSUE THREAD

**Issue by eemelipa** [TheUnderScorer/nx-semantic-release#85]
Analyze commits step fails to "Error: spawn EBADF". This seems to be related to spawning child processes when it executes the git commands. The analyzer has 3440 commits to analyze.

Versions: 
- "@theunderscorer/nx-semantic-release": "2.7.0",
- "nx": "16.6.0",
- nodejs v18.15.0
- Operating system: MacOS Sonoma 14.0

```
auth-client: [9:33:26 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: spawn EBADF
auth-client:     at ChildProcess.spawn (node:internal/child_process:413:11)
auth-client:     at spawn (node:child_process:757:9)
auth-client:     at Object.execFile (node:child_process:348:17)
auth-client:     at Object.exec (node:child_process:232:25)
auth-client:     at /XXX/node_modules/@theunderscorer/nx-semantic-release/src/utils/exec.js:28:42
auth-client:     at new Promise (<anonymous>)
auth-client:     at exec (/XXX/node_modules/@theunderscorer/nx-semantic-release/src/utils/exec.js:18:62)
auth-client:     at listAffectedFilesInCommit (/XXX/node_modules/@theunderscorer/nx-semantic-release/src/common/git.js:63:41)
auth-client:     at isCommitAffectingProjects (/XXX/node_modules/@theunderscorer/nx-semantic-release/src/common/git.js:18:33)
auth-client:     at /XXX/node_modules/@theunderscorer/nx-semantic-release/src/semantic-release-plugin/analyze-commits.js:31:119 {
auth-client:   errno: -9,
auth-client:   code: 'EBADF',
auth-client:   syscall: 'spawn',
auth-client:   pluginName: '[Function: nx-semantic-release]'
auth-client: }
auth-client:  >  NX   spawn EBADF
auth-client:    Pass --verbose to see the stacktrace.

```

**Comment by eemelipa** [comment]
As far as I was able to investigate so far the problem seems to be related to too many `child_process.exec` processes running in parallel. Analyzing 3200 commits went through fine but at around 3400 I started getting errors.
